apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: websocket-server-pdb
  labels:
    app: websocket-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: websocket-server
  unhealthyPodEvictionPolicy: AlwaysAllow