apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websocket-data-pvc
  labels:
    app: websocket-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard