#!/bin/bash

# Test script to debug image URLs in ChatGPT

echo "🔍 Testing Image URL Detection"
echo "This will help debug what URLs DALL-E 3 uses"
echo ""
echo "Instructions:"
echo "1. Open ChatGPT in Chrome with the extension loaded"
echo "2. Open the browser console (F12)"
echo "3. Generate an image with a prompt"
echo "4. Run: window.debugAllImages()"
echo "5. Look for the generated image URL pattern"
echo ""
echo "Common DALL-E 3 URL patterns to look for:"
echo "- https://cdn.openai.com/*"
echo "- https://images.openai.com/*"
echo "- https://oaidalleapiprodscus.blob.core.windows.net/*"
echo "- blob:https://chatgpt.com/*"
echo ""
echo "The debug script will log:"
echo "- All images found"
echo "- Their src URLs"
echo "- Which message they're in"
echo "- Their dimensions"
echo ""
echo "This will help us understand why the addon isn't finding the generated image."