apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: semantest-dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: websocket-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - MAX_CONNECTIONS=1000
      - WORKER_THREADS=2
      - RATE_LIMITING_ENABLED=false
      - AUTHENTICATION_REQUIRED=false

secretGenerator:
  - name: websocket-secrets
    literals:
      - REDIS_URL=redis://dev-redis:6379
      - JWT_SECRET=dev-secret-change-in-production
      - DB_CONNECTION_STRING=sqlite:///app/data/dev.db

replicas:
  - name: websocket-server
    count: 1

images:
  - name: ghcr.io/semantest/workspace/websocket-server
    newTag: latest