apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    spec:
      containers:
      - name: websocket-server
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: CLUSTER_WORKERS
          value: "auto"
        - name: ENABLE_CLUSTERING
          value: "true"
        - name: ENABLE_AUTO_SCALING
          value: "true"
        - name: MIN_INSTANCES
          value: "3"
        - name: MAX_INSTANCES
          value: "20"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - websocket-server
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - high-performance