apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: semantest-production

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: websocket-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn
      - MAX_CONNECTIONS=100000
      - WORKER_THREADS=8

secretGenerator:
  - name: websocket-secrets
    env: secrets.env

replicas:
  - name: websocket-server
    count: 5

images:
  - name: ghcr.io/semantest/workspace/websocket-server
    newTag: v1.0.0  # Always use specific version in production