global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js Server metrics
  - job_name: 'nodejs-server'
    static_configs:
      - targets: ['nodejs-server:3001']
    metrics_path: '/metrics'

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']